---
ID: "cfed1b2c-3e26-4e73-88b7-1d974adaff80"
Parent: "33b22bbf-654b-4961-b3d3-e0a86958bb0b"
Template: "33b22bbf-654b-4961-b3d3-e0a86958bb0b"
Path: /sitecore/templates/Project/Hackathon2025/Headless Tenant/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250308T123957Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\schernetsky@uxbee.nl
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\schernetsky@uxbee.nl
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1d806c51-5e7c-47f9-b13b-2492a2a10b9b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\schernetsky@uxbee.nl
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250308T123957Z
